export const navigator = {
  HOME_NAVIGATOR: 'home_navigator',
  PROFILE_NAVIGATOR: 'profile_navigator',
  PROJECT_NAVIGATOR: 'project_navigator',
  ORTHER_NAVIGATOR: 'orther_navigator',
  WORK_NAVIGATOR: 'work_navigator',
  WORKPLACE_NAVIGATOR: 'workplace_navigator',
  MAIN_NAVIGATOR: 'main_navigator',
  AUTH_NAVIGATOR: 'auth_navigator',
  TABS_NAVIGATOR: 'tabs_navigator',
  TABSADMIN_NAVIGATOR: 'tabsadmin_navigator',
  ADDWORK_NAVIGATOR: 'addwork_navigator',
  MANAGERUSER_NAVIGATOR: 'manageruser_navigator',
  MANAGERWORKPLACE_NAVIGATOR: 'managerworkplace_navigator',
};
