export const screens = {
  HOME_SCREEN: 'home_screen',
  TASK_DETAIL: 'task_detail_screen',
  PROFILE_SCREEN: 'profile_screen',
  LOGIN_SCREEN: 'login_screen',
  REGISTER_SCREEN: 'register_screen',
  PASSWORD_SCREEN: 'password_screen',
  WORKLIST_SCREEN: 'worklist_screen',
  WORKDETAIL_SCREEN: 'workdetail_screen',
  ACCOUNT_SCREEN: 'account_screen',
  WORKPLACE_SCREEN: 'workplace_screen',
  ADDWORD_SCREEN: 'addwork_screen',
  SCHEDULE_SCREEN: 'schedule_screen',
  ADDTEACHER_SCREEN: 'addteacher_screen',
  ADDTASK_SCREEN: 'addtask_screen',
  EDITTASK_SCREEN: 'edittask_screen',
  INFOTEARCHERDETAIL_SCREEN: 'infoteacherdetail_screen',
  FORGOTPASSWORD_SCREEN: 'forgotpasword_screen',
  VERIFICATION_SCREEN: 'verification_screen',
  UPDATEWORKPLACE_SCREEN: 'updateworkplace_screen',
  EDITWORK_SCREEN: 'editwork_screen',
};
